testing parameterized build and colorized message prefix for visible status info

diff --git a/bin/mirror b/bin/mirror
--- a/bin/mirror
+++ b/bin/mirror
@@ -1,51 +1,69 @@
 #!/bin/bash
 
+function timestamp
+{
+    echo $(export TZ=US/Eastern; date +%Y.%m.%d.%H.%M.%S.%:::z )
+}
+
 function usage
 {
-    echo ${0##*/} --repos=repo-file-list
-    echo ${0} requires a repository file with space separated repository names
+    echo ${0##*/} --repo-list=repo-file-list --gitlab-user=username
+
+    echo ${0} requires a repository file with space separated
+    echo       repository urls and push-to user[gitlab-user] 
+    echo The pull from host and user are embedded in the repo list urls.
+
     exit 3
 }
 
-for arg in ${@}; do
-    case ${arg} in
-    --repos=*)
-        repos=${arg##*=}
-        ;;
-    --repos)
-        usage
-        ;;
-    *)
-        echo ${0##*/} --repos=repos-file-list
-        echo ${0} requires repository list argument
-        exit 3
-    esac
-done
-
 function monitor
 {
-    if [[ ! ${repos:-} || ! -e ${repos} ]]; then
+    local gitlab=128.107.15.214     # k8s-node-02
+    # local github_user=davidwalter0
+    local gitlab_user=build.bot.0
+    local github=github.com
+
+    for arg in ${@}; do
+        case ${arg} in
+            --repo-list=*)
+                repo_list=${arg##*=}
+                ;;
+            # --github-user=*)
+            #     github_user=${arg##*=}
+            #     ;;
+            --gitlab-user=*)
+                gitlab_user=${arg##*=}
+                ;;
+            # --repo-list*|--gitlab-user*|--github-user*)
+            --repo-list*|--gitlab-user*)
+                usage
+                ;;
+            *)
+                usage
+        esac
+    done
+
+    if ! mkdir -p /var/lib/mirror; then
+        printf "Failed to create /var/lib/mirror, are you running with the correct permissions?\n\n"
         usage
     fi
-    local gitlab=k8s-node-02
-    local user=davidwalter0
-    local github=github.com
-    mkdir -p /var/lib/mirror
+
     while : ; do
-        echo start new poll run $(date +%Y.%m.%d.%H.%M.%S.%::z)
-        for fullrepo in $(cat ${repos}); do
+        echo $(timestamp) start new poll run
+        for fullrepo in $(cat ${repo_list}); do
+            echo $(timestamp) checking repo ${fullrepo}
+
             repo="${fullrepo##*/}"
             name="${repo##*/}"
             name="${repo%.git}"
-            gitlabrepo=git@${gitlab}:${user}/${repo}
-
+                    
             cd /var/lib/mirror
 
+            gitlabrepo=git@${gitlab}:${gitlab_user}/${repo}
             if [[ ! -e ${name} ]]; then
                 git clone ${fullrepo}
                 cd /var/lib/mirror/${name}
                 git config push.default simple
-                git remote add github ${fullrepo}
                 git remote add gitlab ${gitlabrepo}
             else
                 cd /var/lib/mirror/${name}
@@ -53,18 +71,20 @@ function monitor
 
             if git checkout master &>/dev/null ; then
                 if git pull github master; then
+                    echo $(timestamp) pushing repo ${gitlabrepo} master
                     git push gitlab master
                 fi
             fi
             if git checkout k8s-cfg &>/dev/null ; then
                 if git pull github k8s-cfg; then
+                    echo $(timestamp) pushing repo ${gitlabrepo} k8s-cfg
                     git push gitlab k8s-cfg
                 fi
             fi
         done
-        echo end poll run $(date +%Y.%m.%d.%H.%M.%S.%::z)
+        echo $(timestamp) end poll run
         sleep 60
     done
 }
 
-monitor
+monitor ${@}
